import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { EmptyState } from "@/components/store-shell";
import { money, products, useCart } from "@/lib/store";
import { supabase } from "@/integrations/supabase/client";
export const Route = createFileRoute("/checkout")({ head: () => ({ meta: [{ title: "Secure Checkout — FIRST FAN" }, { name: "description", content: "Complete your FIRST FAN order securely." }, { property: "og:title", content: "Secure Checkout — FIRST FAN" }, { property: "og:description", content: "Delivery and payment for your K-Beauty order." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Checkout });
function Checkout() { const cart = useCart(); const navigate = useNavigate(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); if (!cart.count) return <main className="px-4"><EmptyState title="Nothing to checkout" text="Choose your favourites first." /></main>; async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) { setError("Please sign in before placing your order."); setBusy(false); return; } const trackingCode = `FF-${Date.now().toString().slice(-7)}`; const total = cart.subtotal + (cart.subtotal >= 10000 ? 0 : 350); const { error: orderError } = await supabase.from("orders").insert({ user_id: auth.user.id, tracking_code: trackingCode, customer_name: String(form.get("name")), email: String(form.get("email")), phone: String(form.get("phone")), address: String(form.get("address")), city: String(form.get("city")), total_pkr: total, items: products.filter((p) => cart.items[p.id]).map((p) => ({ id: p.id, name: p.name, quantity: cart.items[p.id], price: p.price })) }); if (orderError) { setError(orderError.message); setBusy(false); return; } cart.clear(); await navigate({ to: "/order-confirmation", search: { code: trackingCode } }); }
return <main className="mx-auto max-w-4xl px-4 py-10 lg:px-8"><h1 className="font-display text-4xl font-bold">Checkout</h1><p className="mt-2 text-muted-foreground">One last step to your new ritual.</p><form onSubmit={submit} className="mt-7 grid gap-6 md:grid-cols-[1.4fr_1fr]"><div className="grid gap-3 rounded-3xl border-2 border-border bg-card p-5"><h2 className="font-display text-xl font-bold">Delivery details</h2><Input name="name" required placeholder="Full name" className="h-12 rounded-xl" /><Input name="email" required type="email" placeholder="Email" className="h-12 rounded-xl" /><Input name="phone" required placeholder="Phone number" className="h-12 rounded-xl" /><Input name="address" required placeholder="Delivery address" className="h-12 rounded-xl" /><Input name="city" required placeholder="City" className="h-12 rounded-xl" /></div><aside className="h-fit rounded-3xl bg-secondary p-5"><h2 className="font-display text-xl font-bold">Payment</h2><label className="mt-4 flex items-center gap-3 rounded-2xl bg-card p-4 text-sm font-bold"><input type="radio" defaultChecked /> Cash on delivery</label><p className="mt-4 flex justify-between font-bold"><span>Total</span><span>{money(cart.subtotal + (cart.subtotal >= 10000 ? 0 : 350))}</span></p>{error && <p className="mt-3 text-sm text-destructive">{error}</p>}<Button disabled={busy} type="submit" className="mt-5 h-12 w-full rounded-xl">{busy ? "Placing order…" : "Place order"}</Button></aside></form></main>; }